name: insta-scheduler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - selenium
  - pytest
  - prompt_toolkit
  - pandas
  - pyyaml
  - pip
  - moviepy
  - ffmpeg
  - transformers
  - pillow
  - croniter
  - pip:
    - webdriver-manager
    - python-dotenv
    - openai-whisper
    - torch --index-url https://download.pytorch.org/whl/cu118   # for GPU
    # - torch --index-url https://download.pytorch.org/whl/cpu   # for CPU
    - torchvision --index-url https://download.pytorch.org/whl/cu118   # for GPU
    # - torchvision --index-url https://download.pytorch.org/whl/cpu   # for CPU 