schedule:
  - time: "13:00"  # Required
    window_hours: 2  # Optional (default: 0)
    max_tasks: 2    # Optional (default: 1)
  - time: "19:00"
  - time: "15:00"
    window_hours: 1

media_list: "config/media_list.csv" 