extra_caption: ' Please rate this video out of 5 stars'
media_list: /home/afzal/Downloads/tikker/data/Likes/videos/tikker_media_list.csv
schedule:
- cron: 0 13 * * *
  max_tasks: 2
  window_hours: 2
- cron: 0 19 * * *
- cron: 0 6 * * *
  window_hours: 1
